### ISSUE TITLE
Additional support for win arm64 wkhtmltopdf

### ISSUE THREAD

**Issue by mawarnes** [JaCraig/Simple-Html-To-Pdf#53]
Would it be possible to add arm64 support in the nuget package. I'd like to run this in windows on parallels running on mac silicon. I have downloaded, installed and testsed the installer here https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.msvc2015-win64.exe

The installer installs to a local folder, and I am n ot sure how it can be added into this project.

I would be happy to add a PR if you're accepting them?

Thank you for putting the project up, it's very useful

**Comment by JaCraig** [comment]
To be honest, I don't update this project too often since wkhtml has been archived, but I've added the arm64 target (v2.1.1). In theory it should pick it up and be fine, but I don't have an ARM machine to test.

If the update doesn't work, you can always take the DLL and drop it into your bin directory for the app that you're building. That would at least tell you if the DLL works on the machine or not. Assuming that works, you can put the DLL in your base app directory and set the build action to Content/Copy if newer. That will ensure that when you build, it shows up in the final build location which is all the library needs to work. The runtime items that it includes are just designed to make the process a little easier.

**Comment by mawarnes** [comment]
I tried running the .net6 code on parallels running windows 11 and wasn't able to succeed

![image](https://github.com/JaCraig/Simple-Html-To-Pdf/assets/221225/20625134-bf50-43c2-a8f2-77d60addeb26)

   at SimpleHtmlToPdf.UnmanagedHandler.WkHtmlBindings.wkhtmltopdf_init(Int32 useGraphics)
   at SimpleHtmlToPdf.UnmanagedHandler.WkHtmlModule.wkhtmltopdf_init(Int32 useGraphics) in C:\Repos\SimpleHtmlToX\Simple-Html-To-Pdf\SimpleHtmlToPdf\UnmanagedHandler\WkHtmlModule.cs:line 176
   at SimpleHtmlToPdf.UnmanagedHandler.BindingWrapper.Load() in C:\Repos\SimpleHtmlToX\Simple-Html-To-Pdf\SimpleHtmlToPdf\UnmanagedHandler\BindingWrapper.cs:line 272
   at SimpleHtmlToPdf.BaseClasses.ConverterBaseClass.Convert(IDocument document) in C:\Repos\SimpleHtmlToX\Simple-Html-To-Pdf\SimpleHtmlToPdf\BaseClasses\ConverterBaseClass.cs:line 48
   at SimpleHtmlToPdf.HtmlConverter.<>n__0(IDocument document)
   at SimpleHtmlToPdf.HtmlConverter.<>c__DisplayClass5_0.<Convert>b__0() in C:\Repos\SimpleHtmlToX\Simple-Html-To-Pdf\SimpleHtmlToPdf\HtmlConverter.cs:line 53
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by mawarnes** [comment]
I think ultimately this is such an edge case it's not worth the effort. The exception seems to suggest the dll is not compatible with the context I would ideally like to run it in. It would be great to understand why it won't work, especially since the assembly appears to be compiled for a win arm64 runtime, perhaps this is not .net core compatible, either way, thank you for the effort, I guess this issue can be closed now!

**Comment by JaCraig** [comment]
That definitely reads like it's x64 and not arm. Which makes sense as the wkhtml guy [didn't have it as a target](https://wkhtmltopdf.org/downloads.html). If you really want, you could probably get it to build from the repo and then just take the wkhtmltox.dll file and drop it in.

That all said, I've actually got it on my list to eventually replace wkhtml when I get a moment. The main issue being time and the replacements require some work by the person consuming the nuget package. Or at least the alternative approaches that I've found do. For example, the most common approach lately is to use Chromium on the back end. I've done it with a test project with a web crawler and it works pretty well, if slower. [This](https://github.com/Sicos1977/ChromiumHtmlToPdf) is a good example. If you're OK installing Chrome on the machine, that project would probably work for you. That said, haven't tried it on an ARM machine. There's also [this one](https://github.com/smartinmedia/Net-Core-DocX-HTML-To-PDF-Converter) which uses LibreOffice under the hood. Also gives you docx export capabilities which is nice. And you can do something similar using OpenXML to create a Word doc by inserting an [alt chunk](https://learn.microsoft.com/en-us/archive/blogs/ericwhite/how-to-use-altchunk-for-document-assembly) with the HTML, CSS, etc. and then using Aspose, etc. to go from the word doc to pdf... That one is less fun though and has formatting issues. Then there's the kind of crazy ones like [Gotenberg](https://github.com/gotenberg/gotenberg) that work great but install as a Docker based API. Great if you're setting up a larger install but less so if you need things more self-contained.
